version: '3.8'

services:
  api:
    build:
      context: .
    image: securemail:v1.0.0
    container_name: securemail_container
    ports:
      - "10000:10000"
    networks:
      - zap-network
    environment:
      HYBRID_ANALYSIS_API_KEY: ${HYBRID_ANALYSIS_API_KEY}
      HYBRID_ANALYSIS_API_URL: ${HYBRID_ANALYSIS_API_URL}
      ML_MODEL_NAME_URI: ${ML_MODEL_NAME_URI}

  zap:
    image: zaproxy/zap-stable
    container_name: zap_container
    ports:
      - "8080:8080"
    networks:
      - zap-network
    depends_on:
      - api
    command: >
      sh -c "until curl -s http://api:10000/health; do sleep 5; done && zap-api-scan.py -t http://api:10000/openapi.json -f openapi -r zap_report.json"
    environment:
      - ZAP_HEADLESS=true

networks:
  zap-network:
    driver: bridge
