version: '3.8'

services:
  api:
    build:
      context: .
    image: securemail:v1.0.0
    container_name: securemail_container
   
    ports:
      - "10000:10000"
    networks:
      - zap-network
    depends_on:
      - zap

  zap:
    image: zaproxy/zap-stable
    container_name: zap_container
    ports:
      - "8080:8080"
    networks:
      - zap-network
    command: >
      zap-api-scan.py -t http://api:10000 -f openapi -r zap_report.json
    environment:
      - ZAP_HEADLESS=true   

networks:
  zap-network:
    driver: bridge
