openapi: 3.0.0
info:
  title: API de Predicción de Phishing
  description: API para predecir correos electrónicos de phishing utilizando un modelo ML y análisis de archivos adjuntos.
  version: 1.0.0
paths:
  /:
    post:
      summary: Predicción de correos electrónicos de phishing
      description: Este endpoint recibe datos de un correo electrónico y devuelve una predicción de si el correo es phishing o no, junto con el análisis de archivos adjuntos.
      operationId: predictEmail
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmailData'
      responses:
        '200':
          description: Predicción exitosa
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: OK
                  predictions:
                    type: array
                    items:
                      type: object
                      properties:
                        model_prediction:
                          type: object
                          properties:
                            label:
                              type: string
                              example: "Phishing"
                            malicious_file:
                              type: boolean
                              example: false
                            probability:
                              type: number
                              format: float
                              example: 0.95
        '500':
          description: Error en el procesamiento de datos
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    example: "Error al procesar los datos: <mensaje de error>"
components:
  schemas:
    EmailData:
      type: object
      properties:
        From:
          type: string
          format: email
          example: "user@example.com"
        To:
          type: string
          format: email
          example: "recipient@example.com"
        Subject:
          type: string
          example: "Phishing email!"
        Body:
          type: string
          example: "Click here to get a free iPhone!"
        Date:
          type: string
          format: date-time
          example: "2025-02-17T14:30:00Z"
        Concatenated_URLs:
          type: string
          example: "http://malicious.link http://another.malicious.link"
        Attachments:
          type: array
          items:
            type: object
            properties:
              filename:
                type: string
                example: "suspicious_attachment.exe"
              content:
                type: string
                format: byte
                example: "BASE64_ENCODED_CONTENT_HERE"
          example:
            - filename: "attachment1.pdf"
              content: "BASE64_ENCODED_CONTENT_1"
            - filename: "attachment2.jpg"
              content: "BASE64_ENCODED_CONTENT_2"
      required:
        - From
        - To
        - Subject
        - Body
        - Date

  securitySchemes:
    apiKey:
      type: apiKey
      in: header
      name: api-key
