name: Auto-CI-SNYK-SAST

on:
  push:
    branches:
      - development

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint pytest httpx pytest-html
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install httpx

    - name: Run pylint and generate report
      run: |
        pylint test/api_fuzzing_test.py test/utils_test.py > pylint_report.txt || true


    - name: Upload pylint report
      uses: actions/upload-artifact@v4
      with:
        name: pylint-report
        path: pylint_report.txt

    - name: Run pytest and generate HTML report
      run: |
        pytest --maxfail=5 --disable-warnings --html=pytest_report.html || true  # No bloquear el pipeline si pytest falla

    - name: Upload pytest HTML report
      uses: actions/upload-artifact@v4
      with:
        name: pytest-report
        path: pytest_report.html

    - name: Show pytest results in job summary
      if: always()
      run: |
        echo "## Pytest Results" >> $GITHUB_STEP_SUMMARY
        echo "[Click here to view the pytest report](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})" >> $GITHUB_STEP_SUMMARY
