name: GitHub Auto SAST Snyk Evaluation

on:
  workflow_run:
    workflows: ["Auto-CI-PYTEST-PYLINT"]
    types:
      - completed

permissions:
  contents: write
  security-events: write

jobs:
  Auto-snyk-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar entorno virtual y instalar dependencias
        run: |
          python3 -m venv venv  
          source venv/bin/activate  
          pip install -r requirements.txt  

      - name: Instalar Snyk CLI
        run: |
          
          wget https://static.snyk.io/cli/v1.666.0/snyk-linux -O /usr/local/bin/snyk
          wget https://static.snyk.io/cli/v1.666.0/snyk-linux.sha256 -O /tmp/snyk-linux.sha256
          echo "5f6f800c1150047f2b6bebe8996db5f25167c8ddcb82741a72634606ba03bdc4  /usr/local/bin/snyk" | sha256sum -c -
          chmod +x /usr/local/bin/snyk

      - name: Ejecutar Snyk Code (SAST)
        run: snyk code test --sarif > snyk-code.sarif || true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_AUTH_TOKEN }}

      - name: Subir resultados de Snyk Code a GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-code.sarif
