name: GitHub Auto Render CD Deployment

on:
  push:
    branches:
      - main  

jobs:
  Deploy-on-Render:
    runs-on: ubuntu-latest

    steps:
     
      - name: Instalar Render CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/render-oss/cli/refs/heads/main/bin/install.sh | sh
    

      - name: Desplegar en Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
          CI: true
        run: |
          render deploys create $RENDER_SERVICE_ID  --output json --confirm --wait
