name: Ejecutar Docker Bench y Mostrar Resultados en el Summary

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  docker_bench_security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Build securemail image
        run: docker build -t securemail:v1.0.0 .

      - name: Run securemail container (detached)
        run: |
          docker run -d --security-opt=no-new-privileges --name securemail_container \
            -e HYBRID_ANALYSIS_API_KEY=${{ secrets.HYBRID_ANALYSIS_API_KEY }} \
            -e HYBRID_ANALYSIS_API_URL=${{ secrets.HYBRID_ANALYSIS_API_URL }} \
            -e ML_MODEL_NAME_URI=${{ secrets.ML_MODEL_NAME_URI }} \
            securemail:v1.0.0

      - name: Run Docker Bench Security
        run: |
            echo "## Resultados de Docker Bench Security" >> $GITHUB_STEP_SUMMARY
            echo "Fecha de análisis: $(date)" >> $GITHUB_STEP_SUMMARY
            echo "### Resumen del Análisis:" >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
            docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
            docker/docker-bench-security:latest \
            sh -c "./docker-bench-security.sh -i securemail-container" | sed 's/\x1b\[[0-9;]*m//g' >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
      - name: Cleanup
        if: always()
        run: |
          docker stop securemail_container || true
          docker rmi securemail:v1.0.0 || true
          docker rmi docker/docker-bench-security:latest || true

     

