name: CI-Pylint-Snyk-SAST

on:
  push:
    branches:
      - development
jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar Pylint
        run: pylint --fail-under=5 $(git ls-files '*.py')
