name: Auto-CI-SNYK-SAST
on:
  push:
    branches:
      - development

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run pylint and generate report
      run: |
        pylint $(git ls-files '*.py') > pylint_report.txt || true

    - name: Upload pylint report
      uses: actions/upload-artifact@v3
      with:
        name: pylint-report
        path: pylint_report.txt

    - name: Test with pytest
      run: |
        pytest
