name: GitHub Auto Render CD Deployment

on:
  push:
    branches:
      - main
      - development  

jobs:
  Deploy-on-Render:
    runs-on: ubuntu-latest

    steps:
      - name: Instalar Render CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/render-oss/cli/refs/heads/main/bin/install.sh | sh

      - name: Desplegar en Render (Main)
        if: github.ref == 'refs/heads/main'
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
          CI: true
        run: |
          render deploys create $RENDER_SERVICE_ID --output json --confirm --wait

      - name: Desplegar en Render (Development)
        if: github.ref == 'refs/heads/development'
        env:
          RENDER_DEVELOPMENT_API_KEY: ${{ secrets.RENDER_DEVELOPMENT_API_KEY }}
          RENDER_DEVELOPMENT_SERVICE_ID: ${{ secrets.RENDER_DEVELOPMENT_SERVICE_ID }}
          CI: true
        run: |
          render deploys create $RENDER_DEVELOPMENT_SERVICE_ID --output json --confirm --wait
