name: GitHub Auto SAST and SCA Snyk Evaluation on Production & Development

on:
  push:
    branches:
      - main
      - development  

permissions:
  contents: write
  security-events: write

jobs:
  Auto-snyk-test:
    runs-on: self-hosted

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar entorno virtual e instalar dependencias
        run: |
          python3 -m venv $HOME/venv  
          source $HOME/venv/bin/activate
          pip install -r requirements.txt   
          # Ejecuta análisis SAST y genera reporte en SARIF
          snyk code test --sarif > snyk-code.sarif || true
          snyk monitor || true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_AUTH_TOKEN }}
 
      - name: Subir resultados de Snyk Code (SAST) a GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-code.sarif

      - name: Subir reporte SAST como artifact (opcional)
        uses: actions/upload-artifact@v4
        with:
          name: snyk-sast-report
          path: snyk-code.sarif
