name: Auto Snyk SAST
on:
  push:
    branches:
      - main
      
permissions:
  contents: write
  security-events: write
  
jobs:
  Auto-Snyk-SAST:
    runs-on: self-hosted
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar entorno virtual y instalar dependencias
        run: |
          python3 -m venv venv  
          source venv/bin/activate  
          pip install -r requirements.txt  

      - name: Ejecutar Snyk Code (SAST)
        run: snyk-linux code test --sarif > snyk-code.sarif || true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_AUTH_TOKEN }}

      - name: Subir resultados de Snyk Code a GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-code.sarif
